In [2]:
a = 0
b = 1
a + b

1

In [3]:
total = 0
for i in range(100):
    total += i
print(total)

4950


In [2]:
import numpy as np
import time
n_samples = 1000000
# Write random floating poin numbers as string on a local csv file
with open('fdata.txt', 'w') as fdata:
    for _ in range(n_samples):
        fdata.write(str(10*np.random.random())+',')

# Read the csv in a list, convert to ndarray (reshape just for fun)
t1 = time.time()
with open('fdata.txt','r') as fdata:
    datastr = fdata.read()
lst = datastr.split(',')
lst.pop()
array_lst = np.array(lst, dtype = float).reshape(1000,1000)
t2 = time.time()
print(array_lst)
print('\nShape: ', array_lst.shape)
print(f'Time took to read: {t2-t1} seconds.')

[[6.91563014 5.89141587 2.60061817 ... 2.57454009 2.9422134  1.96868996]
 [5.13996173 3.75676643 5.13833882 ... 1.40229137 5.79303925 9.09673919]
 [5.59177436 9.1159238  1.32971524 ... 3.05806403 4.70392755 4.15155613]
 ...
 [9.0576312  1.15960034 1.19493087 ... 9.04286327 6.30238802 3.79323268]
 [5.4416149  5.2709007  4.44793283 ... 2.75801235 8.47264377 3.00374391]
 [4.09314665 6.85514387 3.21230988 ... 9.36607835 0.02226063 7.04248293]]

Shape:  (1000, 1000)
Time took to read: 0.732598066329956 seconds.


In [3]:
np.save('fnumpy.npy', array_lst)

In [4]:
array_back = np.load('fnumpy.npy')
array_back

array([[6.91563014, 5.89141587, 2.60061817, ..., 2.57454009, 2.9422134 ,
        1.96868996],
       [5.13996173, 3.75676643, 5.13833882, ..., 1.40229137, 5.79303925,
        9.09673919],
       [5.59177436, 9.1159238 , 1.32971524, ..., 3.05806403, 4.70392755,
        4.15155613],
       ...,
       [9.0576312 , 1.15960034, 1.19493087, ..., 9.04286327, 6.30238802,
        3.79323268],
       [5.4416149 , 5.2709007 , 4.44793283, ..., 2.75801235, 8.47264377,
        3.00374391],
       [4.09314665, 6.85514387, 3.21230988, ..., 9.36607835, 0.02226063,
        7.04248293]])